name: appnodeCI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npm test

    - name: generate tags
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login container Registry docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build image ## depois dos checks de seguranca
      run: docker build -t vboxuser10/conviso-ci:${{steps.generate_tag.outputs.sha}} .

    - name: Push image
      run: docker push vboxuser10/conviso-ci:${{steps.generate_tag.outputs.sha}}

  conviso-sast:
    name: "Conviso SAST"
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli
      env:
        CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Run AST
        run: conviso ast run --vulnerability-auto-close --company-id 908

      - name: Security Gate Check
        run: |
          cat <<EOF > security-rules.yml
          rules:
            - from: any
              severity:
                critical:
                  maximum: 0
                high:
                  maximum: 1
                medium:
                  maximum: 0
                low:
                  maximum: 0
          EOF
          conviso vulnerability assert-security-rules --rules-file security-rules.yml --company-id 908

  conviso-container-scan:
    name: "Conviso Container Scan"
    runs-on: ubuntu-latest
    needs: build
    container:
      image: convisoappsec/convisocli:latest
      env:
        CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Container Scan
        run: |
          export IMAGE_NAME="vboxuser10/conviso-ci"
          export IMAGE_TAG="${{ needs.build.outputs.sha }}"
          conviso container run "$IMAGE_NAME:$IMAGE_TAG" --company-id 908



